version: '3'

services:

  broker-service:
    build: 
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8000:80"
    deploy:
      mode: replicated
      replicas: 1
  # Start Postgres
  postgres:
    image: 'postgres:13.4'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fenix
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  # Start Redis
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./db-data/redis/:/data

  # Start MariaDB
  mariadb:
    image: 'mariadb:10.6'
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: mariadb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: fenix

    volumes:
      - ./db-data/mariadb:/docker-entrypoint-initdb.d

  # Start sftp webdav, and admin interface
  sftp:
    image: 'drakkan/sftpgo:latest'
    ports:
      - "8080:8080"
      - "2022:2022"
      - "10080:10080"
    restart: always
    environment:
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 10080
    volumes:
      - ./db-data/sftp/:/mnt/data/
      - ./db-data/home/:/var/lib/sftpgo

  # Start minio
  minio:
    image: 'quay.io/minio/minio'
    command: server /mnt/data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./db-data/minio/:/mnt/data/
